---
name: CI

on:
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: elixir_dev
  ELIXIR_VERSION: 1.13.4
  GHCR: ghcr.io
  MIX_ENV: dev

jobs:
  build:
    runs-on: ubuntu-latest
    #    strategy:
    #      matrix:
    #        mix-env: [dev, test, prod]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          #      - name: Login to GitHub Container Registry
          #        uses: docker/login-action@v2
          #        with:
          #          registry: ${{ env.GHCR }}
          #          username: ${{ github.actor }}
          #          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.GHCR }}/${{ github.repository }}/${{ env.IMAGE_NAME }}-builder-dev:${{ github.sha }}
          context: .
          build-args: |
            MIX_ENV=${{ env.MIX_ENV }}
            ELIXIR_VERSION=${{ env.ELIXIR_VERSION }}
