---
name: CI

on:
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: elixir_dev
  ELIXIR_VERSION: 1.13.4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Build the Docker image
        run: |
          docker build . \
            --tag ghcr.io/mwilsoncoding/elixir_dev:${{github.sha}} \
            --build-arg MIX_ENV=dev \
            --target builder \
            --driver docker
      - name: Debug
        run: |
          docker images
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Debug
        run: |
          docker images
