---
name: CI

on:
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: elixir_dev
  ELIXIR_VERSION: 1.13.4
  OWNER: mwilsoncoding
  MIX_ENV: dev

jobs:
  build:
    runs-on: ubuntu-latest
    #    strategy:
    #      matrix:
    #        mix-env: [dev, test, prod]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.OWNER }}/${{ env.IMAGE_NAME }}-builder-dev:${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            MIX_ENV=${{ env.MIX_ENV }}
            ELIXIR_VERSION=${{ env.ELIXIR_VERSION }}
      - name: Debug
        run: |-
          docker images
