---
name: CI

on:
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: elixir_dev
  ELIXIR_VERSION: 1.13.4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Build the Docker image
        run: |
          docker build . \
            --tag elixir_dev:${{github.sha}} \
            --build-arg MIX_ENV=dev \
            --target builder \
            -o /tmp/${{env.IMAGE_NAME}}-${{github.sha}}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/${{env.IMAGE_NAME}}-${{github.sha}}.tar
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{env.IMAGE_NAME}}
          path: /tmp
      - name: Load and Run Docker image
        run: |-
          docker load --input /tmp/${{env.IMAGE_NAME}}-${{github.sha}}.tar
          docker run --rm dev:${{github.sha}} mix format --check-formatted
