---
name: CI
on:
  pull_request:
    branches: [main]
env:
  IMAGE_NAME: elixir_dev
  GHCR: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mix-env:
          - dev
          - test
          - prod
        elixir-vsn:
          - 1.11.4
          - 1.12.3
          - 1.13.4
          - 1.14.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.GHCR }}/${{ github.repository }}/${{ env.IMAGE_NAME }}-builder:${{
            matrix.mix-env }}-elixir-${{ matrix.elixir-vsn }}-${{ github.sha }}
          context: .
          build-args: |
            MIX_ENV=${{ matrix.mix-env }}
            ELIXIR_VERSION=${{ matrix.elixir-vsn }}
  run:
    runs-on: ubuntu-latest
    needs: build
    container: ${{ env.GHCR }}/${{ github.repository }}/${{ env.IMAGE_NAME }}-builder:dev-elixir-1.14.0-${{
      github.sha }}
    steps:
      - run: |-
          mix format --check-formatted
