---
name: CI
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mix-env:
          - dev
            #          - test
            #          - prod
        elixir-vsn:
          #          - 1.11.4
          #          - 1.12.3
          #          - 1.13.4
          - 1.14.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/elixir_dev-builder:${{ matrix.mix-env }}-elixir-${{ matrix.elixir-vsn }}-${{ github.sha }}
          context: .
          target: builder
          build-args: |
            MIX_ENV=${{ matrix.mix-env }}
            ELIXIR_VERSION=${{ matrix.elixir-vsn }}
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          #      - uses: actions/cache@v3
          #        with:
          #          path: |
          #            deps
          #            _build
          #            .mix
          #            .hex
          #            .cache
          #          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          #          restore-keys: |
          #            ${{ runner.os }}-mix-
      - run: |
          docker container run ghcr.io/${{ github.repository }}/elixir_dev-builder:dev-elixir-1.14.0-${{ github.sha }} mix format --check-formatted
