---
name: Publish
on:
  push:
    branches: [main]
jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mix-env:
          - prod
        elixir-vsn:
          - 1.14.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/elixir_dev:${{ github.sha }}
          context: .
          build-args: |
            MIX_ENV=${{ matrix.mix-env }}
            ELIXIR_VERSION=${{ matrix.elixir-vsn }}
