---
name: CI
on:
  push:
    branches: [main]
jobs:
  build-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mix-env:
          - dev
          - test
          - prod
        elixir-vsn:
          - 1.14.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            deps
            _build
            .mix
            .hex
            .cache
          key: elixir_dev-${{ matrix.mix-env }}-elixir-${{ matrix.elixir-vsn }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            elixir_dev-${{ matrix.mix-env }}-elixir-${{ matrix.elixir-vsn }}
      - name: Update Cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker build . \
            --tag ghcr.io/${{ github.repository }}/elixir_dev-builder:${{ matrix.mix-env }}-elixir-${{ matrix.elixir-vsn }}-${{ github.sha }} \
            --target builder \
            --build-arg MIX_ENV=${{ matrix.mix-env }}
          docker container create ghcr.io/${{ github.repository }}/elixir_dev-builder:${{ matrix.mix-env }}-elixir-${{ matrix.elixir-vsn }}-${{ github.sha }}
          docker container cp cache:/opt/app/deps .
          docker container cp cache:/opt/app/_build .
          docker container cp cache:/opt/app/.mix .
          docker container cp cache:/opt/app/.hex .
          docker container cp cache:/opt/app/.cache .
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mix-env:
          - prod
        elixir-vsn:
          - 1.14.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/elixir_dev:${{ github.sha }}
          context: .
          build-args: |
            MIX_ENV=${{ matrix.mix-env }}
            ELIXIR_VERSION=${{ matrix.elixir-vsn }}
